### ISSUE TITLE
Error while enabling AutoViaUpdater

### ISSUE THREAD

**Issue by SkyKingPX** [NewAmazingPVP/AutoViaUpdater#2]
Hello,
every time I start my server I get this error:

```
[14:57:02] [Server thread/ERROR]: Error occurred while enabling AutoViaUpdater v3.5 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/format/TextColor
        at spigot.AutoViaUpdater.onEnable(AutoViaUpdater.java:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:546) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:460) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:588) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:413) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3868-Spigot-d2eba2c-ddc9a2d]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.format.TextColor
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more
```

**Comment by NewAmazingPVP** [comment]
Hey there, so sorry, @SkyKingPX, for not following up on this since I had been busy with some other projects, but make sure to test the latest version I have released on GitHub; it most likely solves this bug.

**Comment by SkyKingPX** [comment]
Ok, I will check it out

**Comment by NewAmazingPVP** [comment]
Alright perfect

**Comment by SkyKingPX** [comment]
@NewAmazingPVP I realised that I use AutoPluginUpdater to update Viaversion, so I don't think I would use this

**Comment by NewAmazingPVP** [comment]
Ok alright then I'll close this issue for right now
