### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to autoviaupdater 9.5

### ISSUE THREAD

**Issue by RichWaWa** [NewAmazingPVP/AutoViaUpdater#8]
Attempting to use the plugin on my Velocity 3.4.0 server. I use floodgate, geyser, and AutoViaUpdater. When launching AutoViaUpdater, I get the following terminal error. Tried re-downloading, but still have the issue. I am currently using v9.5 from Spigot.
Could It be the ports I have forwarded? I have a non-standard port configuration for our server.  Geyser uses 25566 and floodgate uses 25565 (Long story)
See Attached Error:
[22:22:32 INFO]: Booting up Velocity 3.4.0-SNAPSHOT (git-4aa9ee77-b455)...
[22:22:32 INFO]: Loading localizations...
[22:22:32 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[22:22:32 INFO]: Loading plugins...
[22:22:33 INFO]: Loaded plugin autoupdategeyser 5.5 by NewAmazingPVP
[22:22:33 INFO]: Loaded plugin autoviaupdater 9.5 by NewAmazingPVP
[22:22:33 INFO] [floodgate]: Took 289ms to boot Floodgate
[22:22:33 INFO]: Loaded plugin floodgate 2.2.3-SNAPSHOT (b114-83fbd6e) by GeyserMC
[22:22:33 INFO]: Loaded plugin geyser 2.6.0-b731 (git-master-c8dadd8) by GeyserMC
[22:22:33 INFO]: Loaded 5 plugins
[22:22:33 ERROR]: Couldn't pass ProxyInitializeEvent to autoviaupdater 9.5
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.moandjiezana.toml.Toml.getBoolean(String)" is null
	at velocity.AutoViaUpdater.onProxyInitialize(AutoViaUpdater.java:68) ~[?:?]
	at velocity.Lmbda$5.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[22:22:33 WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[22:22:33 WARN]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[22:22:34 INFO] [geyser]: Loading extensions...
[22:22:34 INFO] [geyser]: Loaded 0 extension(s)

**Comment by NewAmazingPVP** [comment]
@RichWaWa Try regenerating the config.yml and see if it fixes it. I still haven't had the chance to add an auto reload config feature to this plugin and if that's the reason why sorry for the inconvenience!

**Comment by NewAmazingPVP** [comment]
Actually just found a config bug, make sure java 8 options just have java8 and not java8b. If it says java8b remove the b from the end, I will fix this soon!

**Comment by RichWaWa** [comment]
That Fixed it!
Thank you for the prompt reply!

**Comment by NewAmazingPVP** [comment]
Perfect thank you for reporting the bug, appreciate it! I'll release the new fixed version in a couple of hours.

**Comment by NewAmazingPVP** [comment]
Thank you for informing again, here is the new fixed version https://github.com/NewAmazingPVP/AutoViaUpdater/releases/download/v.9.5.1/AutoViaUpdater-9.5.1.jar
